[package]
name = "ios-empty-window"
version = "0.1.0"
authors = ["Hossein Noroozpour <Hossein.Noroozpour@GMail.com>"]
description = "A simple empty window for ios"
license = "MIT"

[dependencies]
vulkust = { path = "../../vulkust" }

[lib]
crate-type = ["staticlib"]