[workspace]
members = [
    "examples/001-empty-window",
    "examples/002-android-empty-window",
    "examples/003-ios-empty-window",
    "examples/004-scene-loading",
    "vulkust",
]

[profile.release]
lto = true