[package]
name = "simple-game"
version = "0.1.0"
authors = ["Hossein Noroozpour <hossein.noroozpour@gmail.com>"]
description = "A simple game made by Vulkust game engine"
license = "MIT"

[dependencies]
vulkust = { path = "../../vulkust" }
