[package]
name = "vulkust"
version = "0.1.0"
authors = ["Hossein Noroozpour (Thany Hulixer) <hossein.noroozpour@gmail.com>"]
description = "Vulakn based game engine"
license = "MIT"
build = "build.rs"
readme = "../README.md"
keywords = ["game", "engine", "vulkan"]
categories = ["game-engines"]

[features]
fullscreen = []

[dependencies]
# image = "*"
# cgmath = "*"
# gltf = { version = "*", features = ["extras", "names"] }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "*", features = ["libloaderapi", "minwindef",  "windef",  "winerror", "wingdi",  "winuser"] }

[target.'cfg(any(target_os = "linux", target_os = "android", target_os = "macos"))'.dependencies]
libc = "*"

[target.'cfg(any(target_os = "android", target_os = "macos"))'.dependencies]
bitflags = "*"

[target.'cfg(target_os = "macos")'.dependencies]
# This feautres are for debug mode remove them in future
objc = { version = "*", features = ["exception", "verify_message"] }

[build-dependencies]
