[package]
name = "vulkust"
version = "0.1.0"
authors = ["Hossein Noroozpour (Thany Hulixer) <hossein.noroozpour@gmail.com>"]
description = "Vulakn based game engine"
license = "MIT"
build = "build.rs"
readme = "../README.md"
keywords = ["game", "engine", "vulkan"]
categories = ["game-engines"]

[features]
fullscreen = []

[dependencies]
# image = "*"
# cgmath = "*"
# gltf = { version = "*", features = ["extras", "names"] }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "*"
kernel32-sys = "*"
user32-sys = "*"
gdi32-sys = "*"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "*"

[target.'cfg(target_os = "macos")'.dependencies]
# This feautres are for debug mode remove them in future
objc = { version = "*", features = ["exception", "verify_message"] }
bitflags = "*"
libc = "*"
# block = "*"

[build-dependencies]
