[package]
name = "vulkust"
version = "0.1.0"
authors = ["Hossein Noroozpour (Thany Hulixer) <hossein.noroozpour@gmail.com>"]
description = "Vulakn based game engine"
license = "GPL-1.0"

[features]
no-log = []
no-vulkan-debug = []
no-intensive-debug = []
fullscreen = []

[dependencies]
libc = "*"
bitflags = "*"

[target.'cfg(any(target_os = "windows"))'.dependencies]
winapi = "*"
kernel32-sys = "*"
user32-sys = "*"
gdi32-sys = "*"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
# This feautres are for debug mode remove them in future
objc = { version = "*", features = ["exception", "verify_message"] }
block = "*"

[build-dependencies]
